### ISSUE TITLE
what the diffirent between v 15, 15.0 , 15.0.0 ?

### ISSUE THREAD

**Issue by ahsandev2019** [dashpay/docker-dashd#32]
why the version manager of released docker very confused? 
what the diffirent between v 15, 15.0 , 15.0.0 ?

**Comment by nmarley** [comment]
They are tags which currently all point to the same version, though this is not always the case.

For example, if a 0.15.0.1 is released, then `v15` and `v15.0` will point to the new version (0.15.0.1), whereas the `15.0.0` tag will point to the specific older version. Similarly, if a 15.1.0 is released (for example), then `15` and `15.1` will point to that, but `15.0` will point to the latest release in the 15.0 series, which would be `15.0.1` per this example.

**Comment by ahsandev2019** [comment]
thanks
